name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - develop
strategy:
  matrix:
    go: ['1.15','1.18']
jobs:
  check-application:
    # runs-on: ubuntu-lastest
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix }}
      - run: go test
      - run: go run math.go
      