name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-lastest
    # runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      
      - run: go test
      - run: go run math.go
      
      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set UP Docker BuildX
        uses: docker/setup-buildx-action@v1

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: nilsonrsvieira/fc2.0-ci-go:lastest
      
      